###
### GROUP-BY: DATE
###
[kernel]
strict = false
audit = { mode = false, hash = "SHA-256" }
timestamp = { default-time = 00:00:00, timezone = { name = "UTC" } }

[kernel.input]
storage = "fs"

[kernel.input.fs]
dir = "txns"
suffix = "txn"

[transaction]
accounts    = { path = "ok-accounts.toml" }
commodities = { path = "ok-commodities.toml" }
tags        = { path = "none" }


[report]
report-timezone = "UTC"
scale = { min = 2, max = 7 }
accounts = [ "^a:.*", "^e:.*" ]
targets = [ "balance", "balance-group", "register"]

balance       = { title = "BALANCE" }
balance-group = { title = "BALANCE GROUPS", group-by = "date", accounts = ["^not.*"] }
register      = { title = "REGISTER" }


[export]
targets = ["equity", "identity"]
equity = { equity-account = "Equity:Balance" }
