### vim: tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab autoindent
###
### PRICE: COMMODITIES
###

permit-empty-commodity = true

commodities = [
    "â‚¬",
    "$",
    "aaa",
    "bbb",
    "ccc",
    "ddd",
    "TCKLR",
]
